config/routes.rb
Rails.application.routes.draw do

  resources :trips
  resources :activities
  resources :destinations
  resources :users

  get '/', to: 'application#index', as: 'home'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete 'sessions', to: "sessions#destroy"
  post '/activities/new', to: "activities#add_to_trip", as: '/activities/add_to_trip'
  delete '/activities/:id', to: "activities#delete_from_trip", as: '/activities/delete_from_trip'

  # get "/", to: "application#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :trips
  has_many :destinations, through: :trips
  has_many :countries
  has_many :wishlists

  validates :first_name, :last_name, :birthdate, :email, :username, :password, presence: true
  validates :email, :username, uniqueness: true
  # validates :password, length: { in: 4..12 }

  def view_destinations
    self.destinations.map{|destination| destination.to_s}
  end

  def to_s
    self.first_name + " " + self.last_name
  end

  def view_trip_names
    self.trips.map do |trip|
      trip.trip_name
    end.uniq.sort
  end

  def select_trips(trip_name)
    self.trips.select do |trip|
      trip.trip_name == trip_name
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      redirect_to @user
      session[:user_id] = @user.id
    else
      flash[:errors] = @user.errors.full_messages
      render :'users/new'
    end
  end

  def index
    @users = User.all
  end

  def show
    if @user.id != session[:user_id]
      redirect_to User.find(session[:user_id])
    end
  end

  def edit
  end

  def update
    @user.update(user_params)

    if @user.valid?
      redirect_to @user
    else
      # flash[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :birthdate, :email, :username, :password, :private)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.erb
<div class="container">
  <div class="d-flex justify-content-center h-100 smpad">
    <div class="card" id="signup">
      <div class="d-inline-flex card-body justify-content-center smpad">
          <%= simple_form_for @user do |f| %>
          <div class="form-group smpad">
              <%= f.input :first_name%>
          </div>
          <div class="form-group smpad">
              <%= f.input :last_name %>
          </div>
          <div class="form-group smpad">
              <%= f.input :birthdate, as: :date, end_year: Date.today.year - 90,
                                          start_year: Date.today.year,
                                          order: [:month, :day, :year] %>
          </div>
          <div class="form-group smpad">
              <%= f.input :email %>
          </div>
          <div class="form-group smpad">
              <%= f.input :username %>
          </div>
          <div class="form-group smpad">
              <%= f.input :password %>
          </div>

          <div class="form-group smpad">
              <%= f.input :private, label: "Make profile private", as: :boolean, checked_value: true, unchecked_value: false %>
          </div>
      </div>

          <div class="d-inline-flex justify-content-center smpad">
              <%= f.button :submit, class: "btn btn-custom btn-small" %>
          </div>
        <% end %>

    </div>
  </div>
</div>

app/views/users/edit.erb
<div id="homepage">
  <div class="container">
    <div class="d-flex justify-content-center h-100">
      <h2 class="headpad">edit profile</h2>
    </div>

    <%= render "form", patch: edit_user_path %>

  </div>
</div>

app/views/users/index.erb
<div class="container">

  <div class="d-flex justify-content-center h-100 headpad">
    <h3>Welcome to the globe trottr community!</h3>
  </div>
  <div class="d-flex justify-content-center h-100">
    <p>See where fellow globe trottr users are going!</p>
  </div>
  <div class="d-flex justify-content-center h-100">
    <p>P.S. You can make your profile private if you do not wish to share your information with our community</p>
  </div>

  <div class="d-flex justify-content-center h-100 subpad">
  </div>

  <div class="row">
    <div class="col-sm-4">
        <% @users.each do |user| %>
          <% if user.private == nil %>
          <p class="smpad">- - -</p>
            <h5><%= user.username %> is going to:</h5>
              <% user.view_destinations.each do |destination|  %>
                <li><%= destination %></li>
              <% end %>
          <% end %>
        <% end %>
    </div>
    <div class="col-sm-8">
      <% Image.all.each do |image| %>
        <img class="tinypad" height="130" width="230" src="<%= image.url %>">
      <% end %>
    </div>
  </div>

  <div class="smpad">
  </div>

</div> <!-- end of container -->

app/views/users/new.erb
<div id="homepage">

<div class="container">
  <div class="d-flex justify-content-center h-100 ">
    <h3 class="headpad">sign up for globe trottr</h3>
  </div>

  <!-- so this page will be for if you are signing up -->
    <%= render "form", post: @user %>


</div>

</div>

app/views/users/show.erb
<div class="container">

  <div class="d-flex justify-content-center h-100 headpad">
    <h3>Your Upcoming Trips</h3>
  </div>

  <% if @user.trips == [] %>
    <div class="d-flex justify-content-center h-100 smpad">
      <img height="400" src="<%= Image.all.sample.url %>"><br>
    </div>
    <div class="d-flex justify-content-center h-100 smpad">
      <h4>You don't have any upcoming trips!</h4>
    </div>
    <div class="d-flex justify-content-center h-100 smpad">
      <%= button_to "Click here to get started", new_trip_path(@user), method: :get, class: "btn btn-custom btn-sm", id: "btnpad" %>
    </div>
  <% else %>

    <% @user.view_trip_names.each do |trip_name| %>

      <div class="d-flex justify-content-center h-100 smpad">
        <h5><%= trip_name %></h5>
      </div>



        <% @user.select_trips(trip_name).each do |trip|%>
        <div class="d-flex justify-content-center h-100">
          <p><%= trip.start_date.strftime("%m/%d/%Y") %> - <%= trip.end_date.strftime("%m/%d/%Y") %>:
            <%= link_to trip.to_s, trip %></p>
        </div>

        <div class="d-flex justify-content-center h-100">
            <ul>
            <% trip.trip_activities.each do |ta| %>
              <li><%= link_to ta.activity.name, activity_path(id: ta.activity_id, trip_id: trip.id) %></li>
            <% end %>
            </ul>
        </div>
      <% end %>


    <% end %>

    <div class="d-flex justify-content-center h-100 bottom-pad">
      <%= button_to "Create New Trip", new_trip_path(@user.id), method: :get, class: "btn btn-custom btn-sm", id: "btnpad" %>
    </div>
  <% end %>

  </div>