config/routes.rb
Rails.application.routes.draw do

  resources :trips
  resources :activities
  resources :destinations
  resources :users

  get '/', to: 'application#index', as: 'home'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete 'sessions', to: "sessions#destroy"
  post '/activities/new', to: "activities#add_to_trip", as: '/activities/add_to_trip'
  delete '/activities/:id', to: "activities#delete_from_trip", as: '/activities/delete_from_trip'

  # get "/", to: "application#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :destination
  has_many :trip_activities
  has_many :trips, through: :trip_activities
  # before_action :connect_google_api


  def location
    #check trip association --> there's no relationship yet
    self.destination.to_s
  end

  def self.get_photo_url(spot)
    # byebug
    #maxwidth in url changes photo size
    if spot.photos.first == nil
      "Photo Unavailable"
    else
      ref = spot.photos.first.photo_reference
      "https://maps.googleapis.com/maps/api/place/photo?maxwidth=200&photoreference=#{ref}&key=AIzaSyBcF7WmTnqaJVXqW1u4Z2rhHEjOeiaNRtg"
    end
  end


  def self.get_spots(type, id)
    location = Destination.find_by(id: id).to_s
    @client = GooglePlaces::Client.new("AIzaSyBjwhfCwbOrpNN0VU5sc7QspaTmDiBPot8")
    @client.spots_by_query("#{type} near #{location}")
  end

  def self.create_by_api_connection(array, id, search)
    array.each do |spot|
      if self.find_by(name: spot.name) == nil
        self.create(name: spot.name, address: spot.formatted_address, rating: spot.rating, price_level: spot.price_level, photo_url: self.get_photo_url(spot), destination_id: id, search: search)
      else
        self.find_by(name: spot.name)
      end
    end
  end

  def self.select_by_search_and_destination(search, id)
    Activity.all.select do |activity|
      activity.search == search && activity.destination_id == id.to_i
    end
  end

  def format_address_for_search
    self.address.split(" ").join("%20")
  end


end #end of Activity class

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
skip_before_action :authorized, only: [:show]
  #
  # def get_search_image(q)
  #   # byebug
  #   imgs = Google::Search::Image.new(:query =>q).each do |image|
  #     file.write %(<img src="#{image.uri}">)
  #      end
  #      imgs.first
  #      byebug
  # end


  def index
    #get param that are passed through
    #have it render on the page so it can be carried across
    # byebug
    # @image = get_search_image
    @search = params[:search]

    if !!params[:date]
      @date = params[:date]
    else
      @date = params[:trip_activity][:date]
    end
    # byebug
    find_trip

    #fetch from API for the activity spots
    spots = Activity.get_spots(@search, @trip.destination_id)

    #create the activities if they don't already exist (by name)
    Activity.create_by_api_connection(spots, @trip.destination_id, @search)

    #get the activities that match the search and destination
    @activities = Activity.select_by_search_and_destination(@search, @trip.destination_id)
  end

  def show
    find_activity
    find_trip
    @date = params[:date]

    if !!params[:search]
      @search = params[:search]
    end

    @trip_activity = TripActivity.select_trip_activity(trip_id: params[:trip_id], activity_id: params[:id])
  end

  def add_to_trip
    # byebug
    TripActivity.create(trip_id: params[:trip_id], activity_id: params[:activity_id], date: params[:date])
    find_trip
    redirect_to trip_path(@trip)
  end

  def sort_by_rating
    @activities.sort_by { |act| act.rating }
  end

  def destroy
    find_trip
    @trip_activity = TripActivity.select_trip_activity(trip_id: params[:trip_id], activity_id: params[:id])
    @trip_activity.destroy
    redirect_to trip_path(@trip)
  end

  private

  def find_activity
    @activity = Activity.find_by(id: params[:id])
  end

  def find_trip
    @trip = Trip.find_by(id: params[:trip_id])
  end



end #end of ActivitiesController

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/index.erb
<div class="container">

  <div class="d-flex justify-content-center h-100 headpad">
    <h1><%= @search.titlecase %> in <%= @trip.to_s %></h1>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <% @activities.each do |activity| %>
        <% if activity.photo_url != "Photo Unavailable" %>
          <p><img height="80" width="120" src="<%= activity.photo_url %>"> &nbsp&nbsp
          <%= link_to activity.name, activity_path(id: activity.id, trip_id: @trip.id, date: @date, search: @search)%> | Rating: <%= activity.rating %></p>

        <% else %>
        <p><%= link_to activity.name, activity_path(id: activity.id, trip_id: @trip.id, date: @date, search: @search)%> | Rating: <%= activity.rating %></p>
        <% end %>
      <% end %>
    </div>

    <div class="col-sm-5 float-right">
      <iframe width="600" height="450" frameborder="0" style="border:0"
      src="https://www.google.com/maps/embed/v1/search?q=<%= @search%>%20<%=@trip.to_api %>&key=AIzaSyBcF7WmTnqaJVXqW1u4Z2rhHEjOeiaNRtg" allowfullscreen></iframe>
      <ul>
    </div>
  </div>

  <div class="d-flex justify-content-center h-100 bottom-pad">
    <%= button_to "Back to trip", @trip, method: :get, class: "btn btn-custom btn-sm smpad", id: "btnpad" %>
  </div>
</div>

app/views/activities/show.erb
<div class="container">
  <div class="d-flex justify-content-center h-100 headpad">
    <h2><%= @activity.name %></h2>
  </div>
  <% if @activity.trips.include?(@trip) %>
  <div class="d-flex justify-content-center h-100 headpad">
    <h5>You're headed here on <%= @trip_activity.date %>!</h5>
  </div>
  <% end %>

  <div class="row">

    <div class="col-sm-6">
      <% if @activity.photo_url != "Photo Unavailable"%>
        <img height="300" width="450" src="<%= @activity.photo_url %>" alt="Photo Unavailable" class="headpad">
      <% end %>

      <h6>Name: <%= @activity.name %> </h6>
      <h6>Address: <%= @activity.address %> </h6>
      <% if !!@activity.rating %>
        <h6>Rating: <%= @activity.rating %> </h6>
      <% end %>

      <% if !!@activity.price_level %>
        <h6>Price Level: <%= @activity.price_level %> </h6>
      <% end %>
    </div>

    <div class="col-sm-4">
      <iframe width="550" height="420" frameborder="0" style="border:0"
      src="https://www.google.com/maps/embed/v1/search?q=<%= @search%>%20<%=@activity.format_address_for_search %>&key=AIzaSyBcF7WmTnqaJVXqW1u4Z2rhHEjOeiaNRtg" allowfullscreen></iframe>
      <ul>
    </div>

  </div>


  <% if @activity.trips.include?(@trip) %>
  <div class="d-flex justify-content-center h-100 bottom-pad">
    <%= button_to "Back to trip", @trip, method: :get, class: "btn btn-custom btn-sm smpad", id: "btnpad" %>
    <%= button_to "Delete from itinerary", @activity, method: :delete, params: {trip_id: @trip.id, activity_id: @activity.id}, class: "btn btn-custom btn-sm smpad", id: "btnpad" %>
  </div>
  <% elsif !!@trip%>
  <div class="d-flex justify-content-center h-100 bottom-pad">
      <%= button_to "Add to itinerary", activities_add_to_trip_path, method: :post, params: {trip_id: @trip.id, activity_id: @activity.id, date: @date.to_s}, class: "btn btn-custom btn-sm smpad", id: "btnpad" %>
      <%= button_to "Return to #{@search}", activities_path, params: {trip_id: @trip.id, search: @search, date: @date.to_s}, method: :get, class: "btn btn-custom btn-sm smpad", id: "btnpad" %>
  </div>
  <% else %>
  <div class="d-flex justify-content-center h-100 bottom-pad">
    <%= button_to "Return to #{@search}", destination_path(@activity.destination_id), params: {search: @search}, method: :get, class: "btn btn-custom btn-sm smpad", id: "btnpad" %>
  </div>
  <% end %>
</div>


</div>